### ISSUE TITLE
bot_hostname and bot_servername ill defined

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#1]
config.pl needs a better explanation of these in the settings/4 declaration.

**Comment by eazar001** [comment]
I agree some of these settings are still voodoo to me. I'll try to get better explanations of them.

**Comment by eazar001** [comment]
I did one better than an explanation:
I quoted the entire relevant section from the IRC RFC (1459). The info provided in the updated `config.pl` makes it clear that these specifications are mostly trivial anyway. However, for those situations in which a more technical definition is required, one can't do any better than the source itself. Hence this is addressed in commit f431a8e.
