### ISSUE TITLE
Uniform rules for extension interaction

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#13]
We need some sort of rules for extensions so they don't get in each other's way.

There's currently a defacto rule that lets each extension take a name to respond to

?search member/3

?chatty

but already we have chatty, which has a different rule of saying ?chatty then chatty responds to anything you say until ?chatty bye.
Given the nature of chatty, this seems a good design, but I just wonder if we're headed down some road to chaos rather than anarchy.

**Comment by eazar001** [comment]
Right I would agree. I have not reused command names in extensions thus far, and so far it has served me well. I suppose additional sanity checks can be implemented to throw an error at the developer when trying to reuse the extension name as the actual command name.

**Comment by eazar001** [comment]
On second thought perhaps 'error' is too extreme. Maybe a warning message would suffice. I would be content with giving a dev just enough rope to hang oneself.

**Comment by Anniepoo** [comment]
I think you're missing the point, which is to continue to provide a good UX as the number of extensions grows.  Maybe extensions need to register a reserved word  :- yesbot_command(emote, emoticon)

This comes back to the general theme of extensions not being very introspectable.

**Comment by eazar001** [comment]
Indeed then I was. I was considering it from a stability perspective. Nonetheless good user interaction is important, and perhaps your excellent suggestion works well with issue #12

**Comment by eazar001** [comment]
In the interest of merging this with issue #12 to prevent diffusion of both thoughts and possible further discussion, I am closing this issue down.
