### ISSUE TITLE
Need command interface module

### ISSUE THREAD

**Issue by eazar001** [eazar001/yesbot#15]
While completing the process of linking useful commands between `dispatch` and `operator`, it only makes sense to start up a new `command.pl` module to create more abtractions convenient for the developer. The commands here should have the added bonus of lowering visual noise and cognitive overhead. This is not extremely high priority, as some of the more frequently used commands are abstracted in `utilities` so far.

**Comment by eazar001** [comment]
Efforts are already very much underway in `utilities`. Making a separate module for this is perhaps overkill, and not necessarily needed for every use-case. This issue, in hindsight, is superfluous and a waste of time.

**Comment by Anniepoo** [comment]
I'm generally a fan of spare programming - too many layers just makes life more complicated for the soul who's NOT the big expert on the code. And that's generally who you should program for.
