### ISSUE TITLE
chatty needs to handle newlines

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#16]
development on chatty is easiest if you can read the output of debug commands in irc. Most of these are multiline.  Additionally, sometimes ordinary gambits want newlines, particularly with prolog examples.  eazar is making a new multiline pred, move chatty to it when finished.

**Comment by eazar001** [comment]
@Anniepoo, If the default behavior of `priv_msg/2` suits the needs of chatty right now, feel free to use that predicate now. Even if I decide to make changes to `priv_msg/2` to make calls to a `priv_msg/3` with an option list, I'll make sure that the revised version will still have the same effect (in other words, it will still run with your ideal defaults). Just make sure you include `:- use_module(utilities).` to make use of it.

**Comment by eazar001** [comment]
`priv_msg(Long_text, Target)`, will now automatically account for newlines _already_ present in `Long_Text`. If the text is too long to fit within IRC limits then:
`priv_msg(Long_text, Target, [auto_nl(true)])`, will split up the message automatically for you, taking care not to step over the bounds of the 512 char limit.
Other options include
 `priv_msg(Long_text, Target, [auto_nl(true), encoding(Encoding), at_most(5)])`.
The `at_most(N)` option will send at most N segmented lines; this is included as an additional way to control spam. I'll probably be refining and documenting this later. Of course, the `encoding(Enc)` optional will allow you to temporarily set the stream to a valid encoding dispatch the message, and then switch back to utf8. All of these options have what I believe to be reasonable default settings. However if deemed silly, I can refine these later.

**Comment by eazar001** [comment]
Considering this closed with the latest API changes in `utilities.pl`. Re-open if this is still an issue.

**Comment by Anniepoo** [comment]
closed fixed in https://github.com/eazar001/yesbot/commit/da83e96618b6a47f597b40cc90cffa3452fdae7c
