### ISSUE TITLE
King James Programming

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#20]
Be nice to have yesbot pronounce newly posted babblings from http://kingjamesprogramming.tumblr.com/

Even worse, we could have it listen to the channel and train a Markov chain on it, then occasionally say something.

It might sound like dmiles!

=8cO

**Comment by eazar001** [comment]
LOL hahaha - now that's funny.

**Comment by eazar001** [comment]
This sounds like a fun addition though; I'll give it a look some time.

**Comment by eazar001** [comment]
Added by commit 5b1c279921eb67c0db687e26c483c22b61dcff7d
