### ISSUE TITLE
Ring me extension

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#29]
When team members are working on a project together, they often monitor a private IRC channel. 
It can be annoying to know another party is there, but is hacking and not paying attention to IRC window, and you can't raise them.

Solution: Run a local yesbot instance with a plugin that watches the channel for 

?alert  eazar001

Which would fire off a noticable event on eazar001's desktop if he's deep into some hacking and needs poked.

Since 'noticable event' is pretty user dependent, I suggest a setting that yesbot shells out. That 

a) allows user to do whatever is needed to make a noticable and yet not obnoxious notification on their system (the motivating case for this is firing off Gnome notifications, they're not in your face enough). Personally I'd probably have festival read some text.

b) increases reuse. E.g. it would let yesbot be used to fire off some remote process like rebooting apache or some such

It might be useful to append the name of the inciting user and the contents of the rest of the line, to support this application.

A $50 bounty is being offered by The Elgin Works for satisfactory completion of this enhancement.

**Comment by eazar001** [comment]
@Anniepoo , Always with the interesting suggestions =]
Interesting, wondering how reliably I can fire off such notifications. It would seem that yesbot delivering a private message to the user in question would be a minimum feature. Remote processes is definitely interesting, but potentially a security hazard. I'll let you know if I decide to take up the challenge.

**Comment by Anniepoo** [comment]
No no - you're not getting me.

I want to run yesbot on my desktop.  If it wants to alarm, it starts the local alarm process. 
This could, for example, start off a program that does some low level bit twiddling to turn on an army surplus air raid siren and flashes the building lights red. Or something more subtle, like playing a sound.

a pm is not a reasonable solution.

**Comment by Anniepoo** [comment]
Bounty cancelled with daabab35b5fc3e8c0b97eebe3ff2399eb8208180 as I've implemented.ringer
