### ISSUE TITLE
Potential to unnecessarily download large amounts of data

### ISSUE THREAD

**Issue by eazar001** [eazar001/yesbot#3]
Imagining the possibility of downloading huge amounts of data when extracting information from sites. Due to overall goofiness, some servers will not report content-length or content-type. So I should find a nice way to limit bytes examined. I have way to do it, but I'm getting caught in a loop at the moment. I can get desired behavior by using `throw(thread(abort))`, but I would like to find a cleaner way to get this done.

**Comment by Anniepoo** [comment]
Use http_open and just read as much as you want from the site, then close the input stream

**Comment by eazar001** [comment]
Right, this is currently what i'm doing at the moment, but in the case that there is no matching parse ... it would seem that it would download everything. This is okay in most cases, but this could also end up being a 2Gb file for example.

**Comment by eazar001** [comment]
At the moment I think I came up with something to stop if there is no match after 1024 characters. If this works without any hitches, I'll just keep it that way.

**Comment by Anniepoo** [comment]
What are you looking for? the <title> tag?  I'd make it a tad more than 1024, it might be at the bottom of a bunch of keyword/SEO c**p.

**Comment by eazar001** [comment]
Haha, that's true. Yes, it is the tag. Currently it just lazily reads the stream until it finds the tag. When it gets the info it wants, it closes the stream immediately. However some servers are weird and don't report content-type (which when yesbot detcts a text file, jpeg, or whatever it won't even bother to parse), so in those cases I would need a char limit as I can think of no really consistently reliable way to determine text/html if the server doesn't give me that info when I request it. So this is an edge-case I'm trying to account for.

What do you think is a more reasonable cutoff value for the char-limit then? 4096?

**Comment by Anniepoo** [comment]
as of HTTP 1.1 content type is a required header.

**Comment by eazar001** [comment]
I could not get twitter links to work without ignoring their blank `content-type` lines, iirc.

**Comment by eazar001** [comment]
In other words I'm trying to say: You live in a rational and reasonable world. I don't think these "web devs" do. I've witnessed a bunch of bogus artifacts I've had to navigate around unfortunately.

**Comment by eazar001** [comment]
Deleted my last comment as it was pretty unconstructive.

**Comment by eazar001** [comment]
Fixed with latest commit. So I will give any document in the worst case scenario (if a header --in the year 2015 =P ... is not provided), a whole 1,048,576 characters to provide a title. If I can't find a title by then, I'll just figure that they are not ready to rock. I know this is not exactly an ideal solution, but it's the best failsafe I could come up with in one of the worst scenarios I can imagine. I will close this issue for now, but I have a feeling that one of us will be reopening it in the future (given the oddities of HTTP, et. al).
