### ISSUE TITLE
emoticons plugin failing on 8cD

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#4]
<Anniepoo> ?log
<Anniepoo> ?help
<Anniepoo> ?smiley  8cD
<yesbot> darned if I know, half the time they confuse me too

Observed: yesbot says darned if I know, half the time they confuse me too
Expected: Annie is her usual happy self

**Comment by eazar001** [comment]
Thanks for the report! Fixed by commit 62826ff.
