### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#43]
the readme intructions are out of date.

Tried to set up yesbot on partyserver, and found issues:

anniepoo@localhost:~/yesbot$ swipl config.pl
ERROR: /home/anniepoo/yesbot/config.pl:25:
        source_sink `library(irc_client)' does not exist
Warning: /home/anniepoo/yesbot/config.pl:25:
        Goal (directive) failed: config:use_module(library(irc_client))
ERROR: /home/anniepoo/yesbot/config.pl:28:
        source_sink `library(func)' does not exist
Warning: /home/anniepoo/yesbot/config.pl:28:
        Goal (directive) failed: config:use_module(library(func))
ERROR: /home/anniepoo/yesbot/config.pl:29:
        source_sink `library(lambda)' does not exist
Warning: /home/anniepoo/yesbot/config.pl:29:
        Goal (directive) failed: config:use_module(library(lambda))
ERROR: /home/anniepoo/yesbot/config.pl:229:21: Syntax error: Operator expected
ERROR: /home/anniepoo/yesbot/config.pl:238:36: Syntax error: Operator expected
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.2.0)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

**Comment by eazar001** [comment]
Alright, I've added instructions to first install the `irc_client` pack to the README. Thanks.
