### ISSUE TITLE
playing with prolog

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#44]
I'm passing out the link for playing with prolog a lot these days.

youtube.com/channel/UCfWpIHmy5MEx2p9c_GJrE_g

could we have a ?playing   that responds with it?

**Comment by eazar001** [comment]
sure feel free to add it. you have push access as always.

**Comment by eazar001** [comment]
(commit to ref_kb.pl) it's virtually copy/paste

**Comment by eazar001** [comment]
Added @ https://github.com/eazar001/yesbot/commit/759b807247ee3fbfe86f8b59229590bb28f9de07.
